apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    serialize-image-pulls: "false"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.7
controlPlaneEndpoint: 192.168.0.179
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    service-node-port-range: "30000-32767"
    enable-admission-plugins: NodeRestriction
controllerManager:
  extraArgs:
    configure-cloud-routes: "false"
